/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 cabbana_last_withUV.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cabbana_last_withUV.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.252, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.beam7.geometry} material={materials.profile} position={[3849.584, 1452.289, 1107.136]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.beam6.geometry} material={materials.profile} position={[1917.356, 60.079, 1107.135]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.beam5.geometry} material={materials.profile} position={[-60.468, -1414.721, 1107.136]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.beam4.geometry} material={materials.profile} position={[-1955.039, -2844.3, 1107.135]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.beam3.geometry} material={materials.profile} position={[-3849.469, -1433.317, 1107.136]} rotation={[Math.PI / 2, 0, 0]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.beam2.geometry} material={materials.profile} position={[-3849.469, 1433.684, 1107.136]} rotation={[Math.PI / 2, 0, 0]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.beam1.geometry} material={materials.profile} position={[-0.009, 2844.471, 1107.134]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.column8.geometry} material={materials.profile} position={[3872.406, 37.505, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column7.geometry} material={materials.profile} position={[-37.69, 37.474, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column6.geometry} material={materials.profile} position={[-37.644, -2866.92, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column5.geometry} material={materials.profile} position={[-3872.419, -2866.92, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column4.geometry} material={materials.profile} position={[-3872.419, 0.21, -142.132]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column3.geometry} material={materials.profile} position={[-3872.419, 2867.074, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column2.geometry} material={materials.profile} position={[-37.642, 2867.076, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.column1.geometry} material={materials.profile} position={[3872.405, 2867.074, -34.642]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.corner1.geometry} material={materials.profile} position={[3872.382, 2867.068, 1108.786]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.corner8.geometry} material={materials.profile} position={[3872.381, 37.494, 1108.786]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.corner6.geometry} material={materials.profile} position={[-37.669, -2866.91, 1108.786]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.corner5.geometry} material={materials.profile} position={[-3872.326, -2866.915, 1108.786]} rotation={[0, 0, -Math.PI / 2]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.corner3.geometry} material={materials.profile} position={[-3872.324, 2867.072, 1108.786]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.blade5left.geometry} material={materials['02 - Default']} position={[-118.163, -49.45, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade3left.geometry} material={materials['02 - Default']} position={[3791.888, 2854.928, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade4left.geometry} material={materials['02 - Default']} position={[3646.599, 2854.928, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.middleseperator2.geometry} material={materials.profile} position={[-1947.797, -5.161, 1156.044]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.697} />
        <mesh geometry={nodes.blade3right.geometry} material={materials['02 - Default']} position={[3791.888, 49.935, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade2left.geometry} material={materials['02 - Default']} position={[-3632.592, 2854.928, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade1left.geometry} material={materials['02 - Default']} position={[-3777.881, 2854.928, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade6left.geometry} material={materials['02 - Default']} position={[-263.452, -49.45, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade6right.geometry} material={materials['02 - Default']} position={[-263.453, -2854.444, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade5right.geometry} material={materials['02 - Default']} position={[-118.164, -2854.444, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade4right.geometry} material={materials['02 - Default']} position={[3646.599, 49.935, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade2right.geometry} material={materials['02 - Default']} position={[-3632.592, 49.935, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade1right.geometry} material={materials['02 - Default']} position={[-3777.881, 49.935, 1210.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.middleseperator1.geometry} material={materials.profile} position={[0, 1464.305, 1145.065]} rotation={[Math.PI / 2, 0, 0]} scale={0.747} />
        <mesh geometry={nodes.blade2.geometry} material={materials.profile} position={[-3642.461, 1451.979, 1195.787]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade6.geometry} material={materials.profile} position={[-273.322, -1452.401, 1195.787]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade4.geometry} material={materials.profile} position={[3636.729, 1451.979, 1195.787]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade3.geometry} material={materials.profile} position={[3782.019, 1451.979, 1195.787]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade1.geometry} material={materials.profile} position={[-3787.75, 1451.979, 1195.787]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.blade5.geometry} material={materials.profile} position={[-128.033, -1452.401, 1195.787]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.727, 0.737, 0.745]} />
        <mesh geometry={nodes.coltop019.geometry} material={materials.profile} position={[-104.056, 2798.424, 1041.591]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop020.geometry} material={materials.profile} position={[-3804.216, 104.201, 1041.591]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop021.geometry} material={materials.profile} position={[-3803.108, 2798.424, 1041.591]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop022.geometry} material={materials.profile} position={[-102.199, -2800.178, 1041.591]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop024.geometry} material={materials.profile} position={[-109.184, -106.508, 979.069]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop025.geometry} material={materials.profile} position={[-3803.541, -106.508, 979.069]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop026.geometry} material={materials.profile} position={[3805.995, 2798.424, 1041.591]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop027.geometry} material={materials.profile} position={[106.943, 2798.424, 1041.591]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.coltop028.geometry} material={materials.profile} position={[3805.665, 107.468, 979.66]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot3.geometry} material={materials.profile} position={[-3872.37, 2867.035, -1143.344]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot4.geometry} material={materials.profile} position={[-3872.37, 0.18, -1143.344]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.corner4.geometry} material={materials.profile} position={[-3872.326, 0.294, 1108.786]} rotation={[0, 0, -Math.PI / 2]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.foot5.geometry} material={materials.profile} position={[-3872.37, -2867.035, -1143.344]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot6.geometry} material={materials.profile} position={[-37.638, -2867.007, -1143.343]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot7.geometry} material={materials.profile} position={[-41.04, 39.96, -1143.344]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot8.geometry} material={materials.profile} position={[3872.419, 37.39, -1143.344]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot1.geometry} material={materials.profile} position={[3872.419, 2867.035, -1143.344]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.foot2.geometry} material={materials.profile} position={[-37.633, 2867.035, -1143.344]} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes.middleseperator2on1.geometry} material={materials['02 - Default']} position={[-3743.392, -4.702, 1203.201]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.middleseperator2on2.geometry} material={materials['02 - Default']} position={[-3603.962, -4.702, 1203.201]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cabbana_last_withUV.glb')
